#### crowsnest.conf — Logitech C922 Pro

[crowsnest]
log_path: /home/pi/printer_data/logs/crowsnest.log
log_level: quiet
delete_log: true
no_proxy: false

[cam 1]
mode: ustreamer
port: 8080
device: /dev/video0
resolution: 1280x720
max_fps: 30
enable_rtsp: false
rtsp_port: 8554
v4l2ctl: focus_automatic_continuous=0,power_line_frequency=1